spring:
  datasource:
    url: jdbc:h2:~/zerobase
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
#        show_sql: true

logging:
  level:
    org.hibernate.sql: debug